#cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#dnf install mongodb-org -y
#
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#
#systemctl enable mongod
#systemctl restart mongod

- name: Mongodb Setup
  hosts: all
  become: true
  tasks:
    - name: Copy Mongodb repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: mongodb-org -y
        state: present

    - name: Install MongoDB
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.0'
        replace: '0.0.0.0'

    - name: Start MongoDB service
      ansible.builtin.systemd_service:
        state: restarted
        name: mongod
        enabled: true



